### ISSUE TITLE
[DOCS] Upload Source Maps

### ISSUE THREAD

**Issue by smeubank** [getsentry/team-webplatform-meta#62]
### Get a dumb guide then I don't have to think about it anymore. How to upload source maps in CI

**As a** developer
**I want to** upload source maps to sentry
**As a** part of my CI so that I can set it and forget

Persona:
- JS Bundler with plugin support
- JS builds where you need to have it in CI, (whether that is with CLI or GHA)

Origin:
- Google 
- Wizard

- [ ] How to run in CI
  - [ ] GHA doesn't work injects doesn't seem to work
  - [ ] Is there another approach in CI
  - [ ] CI vs plugins
- [ ] How to setup -> release is required?
- [ ] Wizard guides: links to old shit

**Problems:**

```[tasklist]
- [ ] can upload same artefact bundles for release A and B. Right? - yes but something is screwy in UI  - Deduplicate of debugID problem
- [ ] Guide not complete and doesn't include source maps setup it just takes you to the main source maps - main source maps: remove artefact vs release bundle
- [ ] https://github.com/getsentry/sentry-docs/issues/6899
- [x] https://github.com/getsentry/sentry-docs/pull/6956
- [ ] https://github.com/getsentry/sentry/issues/48777
- [ ] https://github.com/getsentry/sentry-javascript/issues/8153
- [ ] https://github.com/getsentry/team-webplatform-meta/issues/68
- [ ] https://github.com/getsentry/telemetry-pm/issues/40
```

### Where is this doc'd or not doc'd today
[Source Maps in JS](https://docs.sentry.io/platforms/javascript/sourcemaps/?original_referrer=https%3A%2F%2Fwww.google.com%2F) shared page besides

**Comment by ale-cota** [comment]
Just for completion, another entry point to the docs might be the error messages you see in the Issue Details page when code can't be unmagnified. Steve C. outlined the scenarios [here](https://www.figma.com/file/Mplyw96iZEnsoTWwQZDcwb/Exploration%3A-Issue-Experience-%2F-Artifact-Bundles?type=whiteboard&node-id=0-1&t=TOfnZFFr83OaDUZy-0), so some of those will point to docs.

And I would also track this issue here (the results of the google and docs search that we need to double check/purge): https://github.com/getsentry/sentry/issues/48777

**Comment by smeubank** [comment]
this is arguably done
